2016/01/26 18:11:02
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:11:04
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:11:31
System.ArgumentNullException: 值不能為 null。
參數名稱: source
   於 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.checkInvoiceProductItems(List`1 items) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 526
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.Validate(InvoiceRootInvoice dataItem) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 193
   於 Model.InvoiceManagement.InvoiceManagerV3.SaveUploadInvoice(InvoiceRoot item, OrganizationToken owner) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\InvoiceManagerV3.cs: 行 48
2016/01/26 18:11:33
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:11:35
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:11:39
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:11:41
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:12:33
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.services.ServiceWorkItem.doDailyTurnKeyCheck() 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\services\ServiceWorkItem.cs: 行 244
2016/01/26 18:14:21
System.ArgumentNullException: 值不能為 null。
參數名稱: source
   於 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.checkInvoiceProductItems(List`1 items) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 526
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.Validate(InvoiceRootInvoice dataItem) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 193
   於 Model.InvoiceManagement.InvoiceManagerV3.SaveUploadInvoice(InvoiceRoot item, OrganizationToken owner) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\InvoiceManagerV3.cs: 行 48
2016/01/26 18:14:23
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:14:25
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:16:29
System.ArgumentNullException: 值不能為 null。
參數名稱: source
   於 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.checkInvoiceProductItems(List`1 items) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 526
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.Validate(InvoiceRootInvoice dataItem) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 193
   於 Model.InvoiceManagement.InvoiceManagerV3.SaveUploadInvoice(InvoiceRoot item, OrganizationToken owner) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\InvoiceManagerV3.cs: 行 48
2016/01/26 18:16:31
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:16:34
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:17:49
System.ArgumentNullException: 值不能為 null。
參數名稱: source
   於 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.checkInvoiceProductItems(List`1 items) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 526
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.Validate(InvoiceRootInvoice dataItem) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 193
   於 Model.InvoiceManagement.InvoiceManagerV3.SaveUploadInvoice(InvoiceRoot item, OrganizationToken owner) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\InvoiceManagerV3.cs: 行 48
2016/01/26 18:17:51
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:17:54
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:19:01
System.ArgumentNullException: 值不能為 null。
參數名稱: source
   於 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.checkInvoiceProductItems(List`1 items) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 526
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.Validate(InvoiceRootInvoice dataItem) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 193
   於 Model.InvoiceManagement.InvoiceManagerV3.SaveUploadInvoice(InvoiceRoot item, OrganizationToken owner) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\InvoiceManagerV3.cs: 行 48
2016/01/26 18:19:03
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:19:05
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:20:07
System.ArgumentNullException: 值不能為 null。
參數名稱: source
   於 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.checkInvoiceProductItems(List`1 items) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 526
   於 Model.InvoiceManagement.Validator.InvoiceRootFormatValidator.Validate(InvoiceRootInvoice dataItem) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\Validator\InvoiceRootFormatValidator.cs: 行 193
   於 Model.InvoiceManagement.InvoiceManagerV3.SaveUploadInvoice(InvoiceRoot item, OrganizationToken owner) 於 c:\Project\VM-SIT04\IFS-EIVO03\Model\AddOn(201412)\InvoiceManagement\InvoiceManagerV3.cs: 行 48
2016/01/26 18:20:09
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/01/26 18:20:11
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
