2016/06/28 13:12:21
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/06/28 13:12:23
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/06/28 13:12:25
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
2016/06/28 13:12:27
System.Net.Mail.SmtpException: 傳送郵件失敗。 ---> System.Net.WebException: 無法連接至遠端伺服器 ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。 127.0.0.1:25
   於 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   於 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   於 System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   於 System.Net.ConnectionPool.GetConnection(Object owningObject, GeneralAsyncDelegate asyncCallback, Int32 creationTimeout)
   於 System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   於 System.Net.Mail.SmtpClient.GetConnection()
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   --- 內部例外狀況堆疊追蹤的結尾 ---
   於 System.Net.Mail.SmtpClient.Send(MailMessage message)
   於 eIVOGo.Published.eInvoiceService.<.cctor>b__3(Object o, ExceptionEventArgs e) 於 c:\Project\VM-SIT04\IFS-EIVO03\eIVOGo\Published\eInvoiceService.asmx.cs: 行 109
